#!/usr/bin/env php
<?php
// app/console

$loader = require_once __DIR__ . '/vendor/autoload.php';

use Romanov\Commands\GreetCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GreetCommand);
$application->run();